/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import classes.PermissaoUtil;
import conexao.Conexao;
import java.sql.Connection;
import classes.Usuario;

public class TelaControleEstoque extends javax.swing.JFrame {

    private Conexao conexao;
    private Connection conn;
    private Usuario usuariologado;

    public TelaControleEstoque(Usuario usuario) {
        initComponents();
        conexao = new Conexao();
        conn = conexao.Conectar();
        this.usuariologado = usuario;

        // Definindo as ações dos botões
        btnCadastrarFornecedor.setActionCommand("CADASTRAR_FORNECEDOR");
        btnCadastrarProduto.setActionCommand("CADASTRAR_PRODUTO");
        btnListarProdutos.setActionCommand("LISTAR_PRODUTOS");


        // Aplica permissões
        PermissaoUtil.aplicarPermissoes(usuariologado,
                btnCadastrarFornecedor,
                btnCadastrarProduto,
                btnListarProdutos,
                btnMovimentarEstoque
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarUsuario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCadastrarFornecedor = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        btnMovimentarEstoque = new javax.swing.JButton();
        lblCadastrar = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        btnListarProdutos = new javax.swing.JButton();
        lblTexto = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(551, 372));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Controle de Estoque");

        btnCadastrarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarUsuario.setForeground(new java.awt.Color(51, 0, 102));
        btnCadastrarUsuario.setText("Cadastrar Usuario");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarUsuario)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCadastrarUsuario))
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnCadastrarFornecedor.setBackground(new java.awt.Color(218, 255, 255));
        btnCadastrarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cadastrar Fornecedores.png"))); // NOI18N
        btnCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFornecedorActionPerformed(evt);
            }
        });

        btnCadastrarProduto.setBackground(new java.awt.Color(218, 255, 255));
        btnCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/CadastrarProduto.png"))); // NOI18N
        btnCadastrarProduto.setDefaultCapable(false);
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        btnMovimentarEstoque.setBackground(new java.awt.Color(218, 255, 255));
        btnMovimentarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/MovimentacaoEstoque.png"))); // NOI18N
        btnMovimentarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimentarEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnCadastrarFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrarProduto)
                .addGap(89, 89, 89)
                .addComponent(btnMovimentarEstoque)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMovimentarEstoque)
                    .addComponent(btnCadastrarProduto)
                    .addComponent(btnCadastrarFornecedor))
                .addContainerGap())
        );

        lblCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        lblCadastrar.setText("Cadastrar Fornecedores");

        lblProduto.setForeground(new java.awt.Color(0, 0, 0));
        lblProduto.setText("Cadastrar Produto");

        lblEstoque.setForeground(new java.awt.Color(0, 0, 0));
        lblEstoque.setText("Movimentação do Estoque");

        btnListarProdutos.setBackground(new java.awt.Color(102, 51, 255));
        btnListarProdutos.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnListarProdutos.setForeground(new java.awt.Color(255, 255, 255));
        btnListarProdutos.setText("Lista de Produtos");
        btnListarProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnListarProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProdutosActionPerformed(evt);
            }
        });

        lblTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texto/Texto(1).png"))); // NOI18N

        lblTexto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texto/Texto(2).png"))); // NOI18N
        lblTexto2.setToolTipText("");

        lblTexto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Texto/Texto(3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProduto)
                        .addGap(94, 94, 94)
                        .addComponent(lblEstoque)
                        .addGap(15, 15, 15)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnListarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblTexto)
                        .addGap(105, 105, 105)
                        .addComponent(lblTexto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(lblTexto3)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadastrar)
                    .addComponent(lblProduto)
                    .addComponent(lblEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto2)
                    .addComponent(lblTexto3)
                    .addComponent(lblTexto))
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(btnListarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProdutosActionPerformed
        new TelaListaProdutos(usuariologado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarProdutosActionPerformed

    private void btnCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFornecedorActionPerformed
        new TelaCadastrarFornecedor(usuariologado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarFornecedorActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        new TelaCadastrarProdutos(usuariologado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnMovimentarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimentarEstoqueActionPerformed
        new TelaMovimentacaoEstoque(usuariologado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMovimentarEstoqueActionPerformed

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        new TelaCadastrarUsuarios(usuariologado).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaControleEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFornecedor;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnListarProdutos;
    private javax.swing.JButton btnMovimentarEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    // End of variables declaration//GEN-END:variables
}
